### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by Kalekdan** [Kalekdan/Pixole-Logger#5]

**Comment by richardbmx** [comment]
@Kalekdan  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project.

[My Portfolio](https://www.behance.net/richardcaseres)

**Comment by Kalekdan** [comment]
@richardbmx by all means. This is currently a really small project so I would not be able to pay you for anything but if you still want to create some logo designs then I would love to see them.

**Comment by richardbmx** [comment]
@Kalekdan  Do not worry, it's a contribution from me, I'll work on some ideas and I'll introduce them to you.

**Comment by richardbmx** [comment]
@Kalekdan  I would like to present this proposal is based on expressing the function of loggin of your project the arrow has some details on the sides to give a relationship with pixels so we can have an own and unique image that expresses very well and that can be remembered easily I hope that you like it if you want some change you just have to request it and with pleasure I can do it

![logo139](https://user-images.githubusercontent.com/35604837/59967662-43ff0780-94fb-11e9-940e-2c2c9a276b72.png)

**Comment by Kalekdan** [comment]
@richardbmx I really like those. Great work! I particularly like the top one.
Would it be possible to see what it would look like saying "PLogger" instead of "Pixole Logger".

**Comment by richardbmx** [comment]
@Kalekdan  Here I present the modification that solocitas

![logo139SOLOP](https://user-images.githubusercontent.com/35604837/60189282-a5c2b880-97fe-11e9-9775-f469b183dc20.png)

**Comment by Kalekdan** [comment]
@richardbmx That's great. Thanks so much! I'll add it to the docs and credit you.

**Comment by richardbmx** [comment]
@Kalekdan  I present here a folder of google drive with all the necessary files to use the logo within the folder you will find different variations of the logo so that you can use it in any way, additional to this there is a file that makes delivery of the copyright for that you can use the logo without problems.

[Google Drive](https://drive.google.com/open?id=1tFJZg-G7cJZE4miL6XjEtO5J4BbPYZV3)

**Comment by Kalekdan** [comment]
@richardbmx Thanks! I'll put it to use!
